### ISSUE TITLE
Plate Tectonics fails on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/decaf#11]
Error is:

```
loader.js:401 Uncaught ReferenceError: _c4pbMJatyk$jWesfHjX0HZGMGaHKKtKiZZYostLJcbT3nE is not defined
    at ec4pbMJatyk$jWesfHjX0HZGMGaHKKtKiZZYostLJcbT3n (rt.jar.sun.reflect.js:190)
    at cheerpjThrow (loader.js:2247)
    at _c4p23edu8colorado4phet9lwjgleLGaalGoda_1b26LWJGLStartupImplemeng4JY7is64BitE1 (plate-tectonics_all.jar.js:1361)
    at _c4p23edu8colorado4phet9lwjgleLGaalGoda_1b26LWJGLStartupImplemeng4Jan3SbXu6cWuHteJhn (plate-tectonics_all.jar.js:1361)
    at Object.eval [as func] (eval at buildContinuations (loader.js:115), <anonymous>:3:696)
    at runContinuationStack (loader.js:387)
    at cheerpjSchedule (loader.js:1110)
    at IDBRequest.inodeReq.onsuccess (cheerpOS.js:655)
ec4pbMJatyk$jWesfHjX0HZGMGaHKKtKiZZYostLJcbT3n @ rt.jar.sun.reflect.js:190
cheerpjThrow @ loader.js:2247
_c4p23edu8colorado4phet9lwjgleLGaalGoda_1b26LWJGLStartupImplemeng4JY7is64BitE1 @ plate-tectonics_all.jar.js:1361
_c4p23edu8colorado4phet9lwjgleLGaalGoda_1b26LWJGLStartupImplemeng4Jan3SbXu6cWuHteJhn @ plate-tectonics_all.jar.js:1361
eval @ VM13149:3
runContinuationStack @ loader.js:387
cheerpjSchedule @ loader.js:1110
inodeReq.onsuccess @ cheerpOS.js:655
IndexedDB (async)
gotParent @ cheerpOS.js:645
idbCreateDirAsync @ cheerpOS.js:662
cheerpjCreateDirAsync @ cheerpOS.js:1549
_h4_52io14UnixFileSystem15createDirectoryE24 @ rt.jar.js:191
_h4F02io4File5mkdirE36 @ rt.jar.js:83
eval @ VM13150:3
runContinuationStack @ loader.js:387
cheerpjSchedule @ loader.js:1110
req.onsuccess @ cheerpOS.js:544
IndexedDB (async)
idbStatAsync @ cheerpOS.js:515
cheerpjStatFileAsync @ cheerpOS.js:1528
_h4_22io14UnixFileSystem21getBooeSSZAttributes0E14 @ rt.jar.js:191
_h4_22io14UnixFileSystem20getBooeSCZAttributesE15 @ rt.jar.js:196
_h4V02io4File6existsE22 @ rt.jar.js:83
_h4V02io4File6mkdirsE37 @ rt.jar.js:83
eval @ VM12941:3
runContinuationStack @ loader.js:387
cheerpjSchedule @ loader.js:1110
(anonymous) @ rt.jar.js:1880
setTimeout (async)
cheerpjHogYield @ rt.jar.js:1880
cjHC @ rt.jar.js:1880
_i4pbNkarcKUa2iG3cuLalgzWCjTq0HashMap6putValE18 @ rt.jar.js:1458
_i4pbNkarcKUa2iG3cuLalgzWCjTGZHashMap3putE17 @ rt.jar.js:1458
eval @ VM13065:3
runContinuationStack @ loader.js:387
cheerpjSchedule @ loader.js:1110
dl.onload @ cheerpOS.js:389
ipfMessage @ loader.js:3524
(index):1 Access to XMLHttpRequest at 'https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse' from origin 'https://phet-dev.colorado.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
loader.js:3062 POST https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse net::ERR_FAILED
```

This sim uses native LWJGL extensions and may not be practical to use CheerpJ.

**Comment by samreid** [comment]
This simulation uses LWJGL 2.9.0.

I tested it again and saw this error message:

```
java.lang.reflect.InvocationTargetException
at java.lang.reflect.InvocationTargetException(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
at edu.colorado.phet.common.phetcommon.application.JARLauncher$SimulationInfo$1.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Caused by: java.lang.UnsupportedOperationException: Unsupported architecture: cheerpj
at edu.colorado.phet.lwjglphet.contrib.LWJGLStartupImplementation.is64Bit(Unknown Source)
at edu.colorado.phet.lwjglphet.contrib.LWJGLStartupImplementation.getPlatform(Unknown Source)
at edu.colorado.phet.lwjglphet.StartupUtils.setupLibraries(Unknown Source)
at edu.colorado.phet.platetectonics.PlateTectonicsApplication.main(Unknown Source)
... 3 more
```
